### ISSUE TITLE
Odd display when 0 sleep hours entered

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/oxleas-adhd#139]
- [x] Fix as per Healthlocker

https://github.com/healthlocker/healthlocker/issues/830

**Comment by MollieCourtenay** [comment]
Just noticed on: https://test-focus.headscapegreenwich.co.uk/tracking-overview
The sleep tracker data displays without Sleep and also has lost the space between hours and Woke up:
<img width="226" alt="screen shot 2017-09-08 at 11 16 39" src="https://user-images.githubusercontent.com/25012688/30207406-59155ee2-9487-11e7-9111-cc50d4b66844.png">

on staging.healthlocker the sleep tracker data displays:
<img width="291" alt="screen shot 2017-09-08 at 11 16 31" src="https://user-images.githubusercontent.com/25012688/30207403-56a3dbac-9487-11e7-843c-7ab5795fb74c.png">

**Comment by MollieCourtenay** [comment]
+ [ ] microseconds is displaying for average.
+ [ ] for today input 0.0 hours sleep.
+ [ ] missing 'Sleep' as per screenshots above.

This has been fixed in healthlocker...


<img width="600" alt="screen shot 2017-09-11 at 11 40 21" src="https://user-images.githubusercontent.com/25012688/30270863-0f741c22-96e6-11e7-801f-509b7c4d973a.png">

**Comment by iteles** [comment]
Apologies @MollieCourtenay, this had not yet been deployed!

**Comment by iteles** [comment]
Ready to test again now @MollieCourtenay

**Comment by MollieCourtenay** [comment]
great thanks!
