### ISSUE TITLE
Teacher: caseload

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#180]
For epic #188 

+ [x] As a teacher, when I log in to HeadScape Focus, I am redirected straight to my caseload.
+ [x] my flash message says 'Logged in as teacher'
+ [x] I can see my caseload of service users I am connected to (do not display carers or care team in caseload).

<img width="343" alt="screen shot 2017-09-11 at 15 13 17" src="https://user-images.githubusercontent.com/25012688/30278982-c6748c96-9703-11e7-9adf-a106ae09f85d.png">

**Comment by katbow** [comment]
I realised after seeing #183 this may require slightly more thought, depending on how a teacher accesses care team. 

Also, how do carers factor into this? They weren't mentioned as teachers being able to message them in that issue, so should this be replaced with care team? Does a teacher need to only see the carers for a service user, or do they need to be able to interact with them in some way, or do carers not need to be displayed at all to a teacher?

**Comment by katyedwards** [comment]
Yeah, not sure - will update both issues when I've heard back...

**Comment by katyedwards** [comment]
Messaging is just between Teacher and care team (like carers at the moment).

I assume the simplest way to implement this UI wise would be:
**Clinician View** - teacher appears in the caseload similar to carers but a different colour - click on a teacher and it looks like the carer interface where the care team just view a message tab and a basic details tab (downside is you might have the same teacher listed multiple times in a caseload, under multiple SUs so @MollieCourtenay might have a better idea).

**Teacher View** - caseload lists SUs.  Click on one and get the message tab - BUT this message tab sends a message to the care team NOT the SU.  They then get the rest of the same tabs as a clinician - goals & strategies, tracking, details - but if something isn't shared they get a holding 'not shared' message on that tab.

I think for now, carers are fairly out of it.

Is that as simple as I think?!  Anyone else got any better ideas?!

**Comment by katbow** [comment]
Okay, I am adding a day label because that will still be a bit different from how it works currently. Right now the user id of the service user is just passed around for loading their room, looking at their details & meds, tracking, goals, etc. But in this case we will need to pass around that for the latter 3 items, but have the room reference the *teacher's* user id to load their own room with the care team. It's a fairly small change, but adding the extra time in case it has any knock on effects with displaying menus or other sections.

**Comment by iteles** [comment]
Pulling the estimate down here a little to deal with just caseload, moving the messaging portion of this to #183 exclusively.

**Comment by katyedwards** [comment]
Design decision from Sarah - teacher's caseload colours will remain the same as the clinician caseload so that SUs are consistently blue throughout the site and clinicians are consistently yellow etc.

Might be _slightly_ confusing for demo purposes as the two dashboards will look similar, but in terms of actual use and consistency it is better like this.

**Comment by katyedwards** [comment]
Looks good to me!
