### ISSUE TITLE
Auto log out after 15 minutes

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#194]
As any type of user, if I have been inactive for 15 mins then I am logged out.

**Comment by katbow** [comment]
estimate is made with the assumption of it applying to all users.

**Comment by katyedwards** [comment]
Confirmation from Oxleas - will be 15mins and will apply to all users.

**Comment by SimonLab** [comment]
PR implementation on HL: https://github.com/healthlocker/healthlocker/pull/1099/files @RobStallion do you think we can apply the same logic?

**Comment by RobStallion** [comment]
@SimonLab I think that this would be ideal. This is very similar to what I was thinking on how we would implement it. Putting it in the auth plug makes a lot of sense as every route is piped though the `:browser` pipeline which contains the `auth plug`.

**Comment by SimonLab** [comment]
based on https://stackoverflow.com/questions/41924627/elixir-phoenix-how-to-implement-session-timeout-expiration

steps:
- [ ] On login, set a new session containing the expiration date time (ie save the expiration time in a cookie)
- [ ] On each request, in the auth plug, get the session with the expiration time and compare it to the current time
- [ ] If the current time < session expiration time just continue, otherwise logout the user

**Comment by katyedwards** [comment]
Working well!
