### ISSUE TITLE
Within Admin system: logged in landing page

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#23]
+ [x] As a super admin, when I log in, I see 3 buttons at the top of the screen.
+ [x] '1. Add staff'
+ [x] '2. Add service user'
+ [x] '3. Add carer'

+ [x] under those buttons, I see a dividing line

+ [x] under the dividing line, I see a list of all the service user accounts, with linked carer accounts below (like HL clinician caseload layout)
+ [x] under the list of SU and carer accounts, I see a dividing line
+ [x] under the dividing line, I see a list of all the staff accounts

**Comment by MollieCourtenay** [comment]
[Admin wireframes.pdf](https://github.com/healthlocker/oxleas-adhd/files/1121684/Admin.wireframes.pdf)

**Comment by RobStallion** [comment]
Will be done when connecting umbrella

**Comment by Cleop** [comment]
Having gone over the issue with @katyedwards - our understanding is that:

- service users will link to the edit service user page which will display their account info but only allowing for editing of their clinicians - see #24 
- Carers names will not have a link to anywhere
- Staff members names will not at this time have the bin symbol to delete them as this issue is in the backlog - see #38

**Comment by katyedwards** [comment]
Yes, looking good
