### ISSUE TITLE
Internal server error on SU Tooklit

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/oxleas-adhd#307]
On Evan B - I'm just getting it on the goals

On my account  and bobby stapler I'm getting it on goals and coping strategies

Any thoughts @RobStallion?

**Comment by RobStallion** [comment]
Can you provide the log in details for those users please @katyedwards so that we can take a look at what could be causing this to happen?

**Comment by katyedwards** [comment]
Sure

evanb@email.com
bob@email.com
katy@mindwaveventures.com

all p/w password

**Comment by RobStallion** [comment]
Looked at the looks on the server for what was causing this error and saw this error message...
```
Request: GET /goal
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function HtmlSanitizeEx.basic_html/1 is undefined (module HtmlSanitizeEx is not available)
```

This directly relates to issue #297. In order for #297 to be resolved we had to remove `html_sanitize_ex` from the `applicaiton` list in the `mix.exs` file. 

However, it appears that `edeliver` uses this list to determine which dependencies can be used in the project. 

A temporary solution to this issue could be to use the `oxleas.script` to run the code as it also runs the code in `prod` and does not encounter this error. However I do not think that this is a good long term solution as it would mean that every time a deployment to the server was done using edeliver; we would have to then `ssh` onto the server and start the application with the command for the script, `systemctl start oxleas.service`

**Comment by RobStallion** [comment]
After doing a bit of light reading ([edeliver readme](https://github.com/edeliver/edeliver), [distillery readme](https://github.com/bitwalker/distillery), [distillery documentation on releases](https://hexdocs.pm/distillery/getting-started.html#understanding-releases)) it looks like the issue is to do with how distillery is building the release of the project. 

Here is the error we get when we run the build using edeliver (which in turn uses distillery)...
![image](https://user-images.githubusercontent.com/15571853/36044844-d684ecb8-0dcb-11e8-8269-f534efe6bf1f.png)

```
==> Including ERTS 9.0 from /usr/lib/erlang/erts-9.0
==> Generating boot script
==> Release failed, during .boot generation:
        Undefined applications: [xmerl]
```

However, if I run a build using just `distillery` on it's own I get the following...

![image](https://user-images.githubusercontent.com/15571853/36044911-037a5302-0dcc-11e8-9ee7-a5b8bb3568ba.png)

```
  xmerl-1.3.16
    from: /usr/local/Cellar/erlang/20.2.2/lib/erlang/lib/xmerl-1.3.16
    applications:
      :kernel
      :stdlib
    includes: none
```

![image](https://user-images.githubusercontent.com/15571853/36045456-b37d055a-0dcd-11e8-82b2-9c899c640f75.png)

It appears as though when I am using just `distillery` it is able to find the package `xmerl` but when we use `edeliver` it cannot. 

In order to see why this might be happening I have taken two screenshots of the same package being installed. The first is from the `edeliver` build...

![image](https://user-images.githubusercontent.com/15571853/36045379-6f85c6f2-0dcd-11e8-8d03-0204bdbd9fdd.png)

And the second is from the `distillery` build...
![image](https://user-images.githubusercontent.com/15571853/36045389-79233ed8-0dcd-11e8-9bc4-4cfba8fb1c05.png)

It appears as though they are reading their files from different paths. Going to look into why this is happening and try to get `edeliver` to read from the same path as `distillery`.

**Comment by nelsonic** [comment]
@RobStallion great detective work! 🔍 My advice would be to open issues/questions _everywhere_ to get help from the _creators_ of these modules. failing that I can help pair-debug this if you are free.

**Comment by RobStallion** [comment]
After looking at the file path for the `edeliver` build above I noticed that I do not have a path like this locally. However this exact path does exist on the server. 

This leads me to believe that the issue is with `edeliver` not being able to find the file for `xmerl` on the staging server.

**Comment by RobStallion** [comment]
Have managed to resolve this issue now. `erlang-xmerl` needed to be installed on the server. 

Ran the following commands on the staging server
```
apt-get update
apt-get install erlang-xmerl
```

Next time I ran the build it was successful.

Next steps

- Install `erlang-xmerl` on the live server
- Write some documentation for this.

**Comment by katyedwards** [comment]
@RobStallion was the fix for this deployed?  I'm still having problems this morning on goals, coping strategies and now tracking overview as soon as I have saved any tracking data.

We're going to struggle to test the 'please test' issues if we can't access stuff!

**Comment by RobStallion** [comment]
@katyedwards this was finished quite late on Friday night so there was not time to get it merged in then. It has been merged not too long ago now though so will do a deployment to staging.

**Comment by katyedwards** [comment]
This one seems to be sorted, but I'm getting it again on the clinician caseload :o(

Have updated that issue, but will close this one!
