### ISSUE TITLE
create a copy of HL that is de-coupled from SLaM/epjs

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#52]
@MollieCourtenay I've left your original comments below and expanded here:

As Oxleas use a system other than ePJS (Rio), we need to decouple the currently Healthlocker application from ePJS database so that Healthlocker can work for the Oxleas team without being dependent on a system they don't use.

This consists of:
+ Removing the links to connect to SLaM from the account page (note, this will leave us with a fair amount of redundant code) #43 
+ Alter connecting as carer functionality to not verify data against ePJS but to do so through our database (assuming same data is used) #51 
+ Clinicians functionality: there are some big question marks for us over how clinicians connect and how we know what their caseload is - this could get quite big #51 
+ Care team contacts for all users will no longer come from ePJS but our own database #56
+ Consent: there are checklist items that appear based on ePJS data, this will need to be altered so that they are conditional on database data - @katyedwards Notes this will happen on paper, team will sign up users
+ Copy changes throughout - training separately #20 

---
**Original issue**

I am not sure exactly how to expand on this

Includes:
#43 
#51

Note: 
it may be a good idea to copy, decouple, and then copy that decoupled version and pop one of those decoupled versions some where, and work the other one in to this Oxleas service.
This is incase this is a requirements from some other organisation in the future.

**Comment by iteles** [comment]
These are the points I had previously written for this:
+ Removing the links to connect to SLaM from the account page (note, this would leave us with a fair amount of redundant code)
+ Alter connecting as carer functionality to not verify data against ePJS but to do so through our database (assuming same data is used)
+ Care team contacts for all users will no longer come from ePJS but our own database
+ Consent: there are checklist items that appear based on ePJS data, this will need to be altered so that they are conditional on database data 
+ Clinicians functionality: there are some big question marks for us over how clinicians connect and how we know what their caseload is - this could get quite big
+ Copy changes throughout

**Comment by reddog** [comment]
re:

> Consent: there are checklist items that appear based on ePJS data, this will need to be altered so that they are conditional on database data

#45 addresses removing service user self-initiated signup.

**Comment by katbow** [comment]
See [here](https://github.com/healthlocker/healthlocker/issues/954) for work being done on Healthlocker to achieve this.

**Comment by RobStallion** [comment]
Closing this as the approach to how the application has been created is no longer reflected in this issue. 

All the epjs functionality has been moved into it's own application, separate to HL, which can be found [here](https://github.com/healthlocker/epjs_app)

Healthlocker is in the process of replacing database calls it made to epjs with API calls to epjs_app. The current progress can be found [here](https://github.com/healthlocker/healthlocker/pull/953). Currently being blocked from merge due to testing issues but this will not affect building the features for Oxleas app. See [here](https://github.com/healthlocker/healthlocker/issues/941#issuecomment-319330577) for more info. 

The oxleas app is now going to be built with the features that only apply to it specifically. All other functionality will be in the HL repo.
