### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#94]
+ [x] Make sure we have one 

Work needed to be done in order to create an SSL Certificate for Oxleas

- [x] Look into the creation of the custom subdomain name. Links to #49. (SLaM is doing this)

- [x] Follow instructions found in [this readme](https://github.com/dwyl/learn-heroku/blob/master/SSL-certificate-step-by-step-setup-instructions.md) for Let's Encrypt free SSL. Going to have to be adapted to work with Azure environment (T4h)

- [x] Install Nginx on the virtual environment. (T25m)

- [x] Configure Nginx on the server following instructions found [here](https://mediatemple.net/community/products/developer/204405534/install-nginx-on-ubuntu) to make sure it works as expected (T1h)

- [x] Configure `nginx.config` file in the project so that it uses the the SSL certificate on the server and make sure port settings are correct (T4h)

**Comment by markwilliamfirth** [comment]
@nelsonic please can you let us know if you have time to tackle this before 24th August? Otherwise we will need to assign this one to @katbow and @RobStallion 

Linked to #49

**Comment by MollieCourtenay** [comment]
@nelsonic I'd appreciate your advice on the fact that Oxleas Healthlocker will be on a subdomain of an existing site http://headscapegreenwich.co.uk/   - whether we should advise them to get one SSL certificate for their whole site / or whether we do need to get an individual one for the  focus.headscapegreenwich.co.uk ??

**Comment by markwilliamfirth** [comment]
@katbow @RobStallion please take a look at this one and:

- Provide a time estimate
- Get input from Tony if you need it
- Post an update here on what's required from SLaM

**Comment by iteles** [comment]
@katbow @robstallion @molliecourtenay Sorry we didn't see this one earlier! letsencrypt lets you cover sub domains and the root with a single certificate so this shouldn't be an issue :+1:

**Comment by katyedwards** [comment]
@iteles thanks for that - great news!

**Comment by markwilliamfirth** [comment]
Posting Nelson's let's encrypt doc here as might be useful: https://github.com/dwyl/learn-heroku/blob/master/SSL-certificate-step-by-step-setup-instructions.md

(might be different for Azure?)

**Comment by reddog** [comment]
@markwilliamfirth As part of the whole project deployment, can this  be started well in advance of the end of week to accommodate any potential issues?

**Comment by markwilliamfirth** [comment]
@RobStallion to add a time estimate after looking at the documentation

**Comment by reddog** [comment]
@markwilliamfirth How much time is being set for reading the documentation and when will that happen?

**Comment by reddog** [comment]
@markwilliamfirth Thanks for that.  So that's 25 minutes for reading documentation *and* implementing?  When will that be completed?  Is it also part of the `nginx` configuration?

**Comment by markwilliamfirth** [comment]
@reddog 25 minutes for Rob to look at the SSL documentation and then provide a rough time estimate which includes the following:

- Thoroughly reading the SSL documentation
- Setting up the SSL cert

Rob will be looking into it this morning

@RobStallion please can you answer @reddog 's question about whether nginx config is part of SSL set up once you have had a look at the steps to set up the SSL?

**Comment by RobStallion** [comment]
Work needed to be done in order to create an SSL Certificate for Oxleas

- [ ] follow instructions found in [this readme](https://github.com/dwyl/learn-heroku/blob/master/SSL-certificate-step-by-step-setup-instructions.md) for Let's Encrypt free SSL. 

- [ ] Install Nginx on the virtual environment.

- [ ] Configure Nginx following instructions found [here](https://mediatemple.net/community/products/developer/204405534/install-nginx-on-ubuntu)

**Comment by RobStallion** [comment]
installed nginx on `Oxleas-HL-Test` environment

**Comment by RobStallion** [comment]
Going to install nginx on the `Oxleas-HLLive` server and check the configuration on there as this is not in use right now.

**Comment by RobStallion** [comment]
After installation this is the message that displays when you go to `51.140.116.95`

![image](https://user-images.githubusercontent.com/15571853/29710030-9606967e-8986-11e7-86cf-fe93a2e3ec89.png)

**Comment by katyedwards** [comment]
It's alive!  http://focus.headscapegreenwich.co.uk/

@RobStallion over to you to finish the last steps to get the SSL set up, although we need to get any HL bits finished first (by lunchtime!)

**Comment by RobStallion** [comment]
Hey @katyedwards Thanks for getting back to us with this. I can see that it works which is great but I just had a couple of questions.

As there are 2 servers I was wondering if they were going to get a url for each? At the moment the `Oxleas-HL-Test` server is the one that is pointing to the url http://focus.headscapegreenwich.co.uk/. The reason I ask is because I was under the impression that `Oxleas-HLLive` was going to be pointing at this url. That way we could always have the site running on `Oxleas-HLLive` and we could use the `Oxleas-HL-Test` server to make and test changes without effecting the site.

@reddog Should we use `Oxleas-HLLive` for testing now and leave the `Oxleas-HL-Test` server running as the _"live site"_?

**Comment by katyedwards** [comment]
@RobStallion Thanks - I had asked about that in an email... are we currently using the test server only?

We do want that URL pointing to whichever server will be used as the live one.  

Presumably it would be useful to get Oxleas to create another subdomain like staging.focus.headscapegreenwich.co.uk or something to use on the test server. 

Could this then be covered by the same SSL certificate?

@reddog for speed since the url is pointing at the test server, it would make sense to use live for testing and use test for live - but you'll have to advise if there are any downsides to doing this!

**Comment by reddog** [comment]
@RobStallion I'm not sure exactly what the question is here.  Was the FQDN of `focus.headscapegreenwich.co.uk` matched to `Oxleas-HL-Test` by ourselves?

At the moment both environments should be at the same setup and code point, shouldn't they?  Is that the case?

Where are the labels `Oxleas-HLLive` and `Oxleas-HL-Test` set?

Whatever the live site is, namely `focus.headscapegreenwhich.co.uk` it should be referred to as `Oxleas-HLLive` and **not** `Oxleas-HL-Test` otherwise there is a fair chance that at some point in the future someone will become confused and do the wrong thing in the wrong environment.

@RobStallion Which is quickest?  Change the name -> FQDN relationship?  Something else?

End result probably needs to be:

`Oxleas-HLLive` -> `focus.headscapegreenwich.co.uk`
`Oxleas-HL-Test` -> `somethingelse.headscapegreenwich.co.uk`

**Comment by RobStallion** [comment]
@reddog SLaM provisioned two different Azure instances for Oxleas, one called `Oxleas-HLLive` and another called `Oxleas-HL-Test`. 
![image](https://user-images.githubusercontent.com/15571853/30033054-d6fed5b2-9190-11e7-89a6-c05a0f4b7767.png)
![image](https://user-images.githubusercontent.com/15571853/30033065-e34fba3e-9190-11e7-887c-94aad9e8fc64.png)

They are two different servers, each with their own IP address. I thought that the `Oxleas-HLLive` server would be using the http://focus.headscapegreenwich.co.uk/ URL so I was surprised when I saw that the `Oxleas-HL-Test` redirected to it. 

My thoughts on this were similar to what you have written at the end of your comment [here](https://github.com/healthlocker/oxleas-adhd/issues/94#issuecomment-326952297), but as that is not the case at the moment, I was asking if you would want us to use `Oxleas-HLLive` for testing at the moment.

To answer your questions, SLaM made it so the IP Address of the `Oxleas-HL-Test` server goes to the http://focus.headscapegreenwich.co.uk/ url. I'm not sure how long it would take to change the server names or the FQDN relationship. This would be something that SLaM would have to do so they would be in a better position to answer that.

**Comment by RobStallion** [comment]
@katyedwards I don't see an email from you sorry. Could you please try sending it again to my dwyl email. 

I don't know if the test site really needs a sub-domain as it would mainly be for us, dwyl and mindwave, to check new features and bug test before pushing the changes to the live site. As no real data would be entered on the test site, I would imagine that it would not need to be encrypted so we would not need to worry about another SSL certificate.

**Comment by reddog** [comment]
@RobStallion Would it be good to have the test and live sites as close to each other as possible in terms of configuration?  That would help ensure we were developing/testing with the correct set up already in place, and should help ensure we don't have some types of unexpected issue when moving live?

**Comment by reddog** [comment]
@RobStallion Regarding the live FQDN being pointed to the `test` site, this is quite possibly down to me - I may have given Oxleas the wrong IP address.  I'll see what we can do.

How easy/difficult is it to switch the labels for the machines over `Oxleas-HL-Test` <-> `Oxleas-HLLive`?

**Comment by RobStallion** [comment]
@reddog Sorry again but I am not certain as SLaM provisioned these servers for us and named them in the process.

**Comment by reddog** [comment]
@RobStallion Okay, thanks for that.

**Comment by katyedwards** [comment]
@RobStallion sorry - that was a bit unclear from me - I'd mentioned in an email (to Ines I think) that I wasn't sure which environment we were using for Oxleas but it has been clarified here already, thanks!

**Comment by reddog** [comment]
DNS changes have been made as follows:

`
 Name:	focus.headscapegreenwich.co.uk
 Address: 51.140.116.95

 Name:	test-focus.headscapegreenwich.co.uk
 Address: 51.140.117.78
`

It may take a little while for the `focus.headscapegreenwich.co.uk` DNS *change* to propagate.  The new entry, `test-focus` should be available immediately.

@RobStallion Can you please confirm my previous query if the two environments are currently identical?

**Comment by reddog** [comment]
@RobStallion Can you please note what steps are required to complete this issue, breaking anything down that's larger than two hours.

**Comment by reddog** [comment]
@RobStallion re your comment at https://github.com/healthlocker/oxleas-adhd/issues/94#issuecomment-324696175 :

> Follow instructions found in [this readme](https://github.com/dwyl/learn-heroku/blob/master/SSL-certificate-step-by-step-setup-instructions.md) for Let's Encrypt free SSL. Going to have to be adapted to work with Azure environment (T4h)

That readme looks great for a Heroku installation.  Since we're on an Azure Linux VM, there are really clear steps listed on the `certbot` site, see https://certbot.eff.org/

**Comment by RobStallion** [comment]
@reddog Thanks for looking into this. I have seen the documentation on their site but I will be looking at the readme produced by @nelsonic first as it contains steps for what he has done when he ran into issues. Also although the readme was written for Heroku, step 4 to 7 should be able to be applied to the Azure VM.

**Comment by reddog** [comment]
@RobStallion Thanks for that.

The first line on step 4 of Nelson's doc does suggest going direct:

> certbot installation instructions for various platforms: https://letsencrypt.org/getting-started

In Nelson's doc installation of certbot is via brew. I'm not sure that is immediately available on Ubuntu?

Further along there are notes on satisfying certbot's requirement for a verification page to be made available. The instructions there won't immediately work but the EFF certbot document gives step by step details of how to make that file available.

**Comment by reddog** [comment]
Will this specific issue also be implementing force HTTPS only access, ie redirect all HTTP requests to HTTPS?

**Comment by RobStallion** [comment]
@reddog Regarding your comment [here](https://github.com/healthlocker/oxleas-adhd/issues/94#issuecomment-327399063) I feel confident implementing the README for the Azure environment so I will be starting there. 

With regards to your [comment here](https://github.com/healthlocker/oxleas-adhd/issues/94#issuecomment-327404465) this is done in the `nginx` configuration file on [these lines](https://github.com/healthlocker/healthlocker/blob/master/nginx.config#L2-L16)

**Comment by RobStallion** [comment]
Following on from step 4 of [README](https://github.com/dwyl/learn-heroku/blob/master/SSL-certificate-step-by-step-setup-instructions.md#step-4-run-certbot-command-manual-setup)

Have installed certbot on the test server 
![image](https://user-images.githubusercontent.com/15571853/30104347-44f80b3a-92ed-11e7-87e5-4af148dfe536.png)

**Comment by RobStallion** [comment]
I am going to be deploying my own repo to the Azure server in order to try and generate the SSL certificate.

The reasons for this are..

I want to be able to quickly add/update files and folders that will be needed when generating the certificate without having to wait for them to be reviewed.

To keep the oxleas repo clean and try to keep unnecessary commits and unused files to a minimum (also seems to be the approach that was taken in the readme mentioned above)

**Comment by RobStallion** [comment]
That appears to have worked but I haven't taken the screen shot 😥 (My connection to the ssh froze but the files are now created)

![image](https://user-images.githubusercontent.com/15571853/30106079-4e873e28-92f2-11e7-8d65-e0e75c8e8e13.png)

**Comment by RobStallion** [comment]
Moving on to `nginx` config on the server. 

My first step will be to follow along with `HL issue #841` from [here](https://github.com/healthlocker/healthlocker/issues/841#issuecomment-311647384). 

Reason I am following along from this point is because `nginx`is currently running but not being used when the firewall rules are redirecting all incoming traffic to port 4000.

**Comment by RobStallion** [comment]
I have removed the firewall setting from the server with the following command 
```
sudo iptables -t nat -D PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 4000
```

and then added the following line to the `nginx` config file found at `/etc/nginx/sites-enabled/default`

`proxy_pass http://localhost:4000;`

Added that line to the `location / {` options.

When the app isn't running this is the result
![image](https://user-images.githubusercontent.com/15571853/30112081-fa57e026-9307-11e7-9d95-4732996c623d.png)

When it is running using the `mix edeliver start production` command this is the result
![image](https://user-images.githubusercontent.com/15571853/30112172-3a2d0438-9308-11e7-9475-6b1fc4410a70.png)

Success! 😁 (I was using a test repo. This is not the Oxleas site)

Next step is to further configure the nginx settings to make sure it is using the SSL certificate (and any other settings that may be needed, for example redirecting all HTTP requests to HTTPS). Will be based heavily off of the [config file used in HL](https://github.com/healthlocker/healthlocker/blob/master/nginx.config)

**Comment by RobStallion** [comment]
I keep getting `nginx` errors when I am using the settings from the `HL nginx` config. 

Going through line by line to see what is causing the issue and why

**Comment by RobStallion** [comment]
Config appears to be working and using the SSL certificate now.

![image](https://user-images.githubusercontent.com/15571853/30115633-392e8808-9313-11e7-80ee-7d99038f610b.png)


If I type in the IP address for the server as shown in the picture above, I get the following...

![image](https://user-images.githubusercontent.com/15571853/30115689-63d13c40-9313-11e7-8318-f1a4525b263d.png)

Next step is to stop using my test application and use the real Oxleas app. Should not have to change any settings for this.

**Comment by RobStallion** [comment]
![image](https://user-images.githubusercontent.com/15571853/30116519-ac5ff7b0-9315-11e7-8617-650787704202.png)

**Comment by katyedwards** [comment]
Lovely job!
